server:
  port: 8081

 
security:
  oauth2:
    client:
      clientId: AccountMicroService
      clientSecret: ${ACCOUNT_MICROSERVICE_PASSWORD}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server    
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 
             
spring:
   datasource:
        url: jdbc:mysql://localhost:3306/newdb
        username: root
        password: root
        driver-class: com.mysql.jdbc.Driver 

jpa:
    database-platform: org.hibernate.dialect.MySQLDialect       
    show-sql: false
    hibernate.ddl-auto: create   


    