eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:  
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false          

authserver:
    hostname: localhost
    port: 8899
    contextPath: userauth
       
---

    
#Configuration on Docker Container                  
spring:
    profiles: docker
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.59.103:8761/eureka/
      
# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
    hostname: 192.168.59.103
    port: 8899
    contextPath: userauth
    
# Define the port where the API gateway server would be running. This could always be port 8080
# since each docker container has it's own IP
server:
  port: 8080      
    