server:
    port: 8075
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/donors
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
 
security:
  oauth2:
    client:
      clientId: DonorsMicroService
      clientSecret: ${DONORS_MICROSERVICE_PASSWORD}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server     
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 

       